export type AuthorType = {
  id: string;
  name: string;
};

export interface BookProps {
  id: string;
  title: string;
  type: string;
  publishedAt: string;
  stock: number;
  price: string;
  authors: { author: AuthorType }[];
  averageRating: number;
  ratings: number;
  shippingFee: number | null;
  urlImg: string;
}

export interface shoppingCartItemProps extends BookProps {
  quantity: number;
}

export type BookDetailProps = Omit<
  BookProps,
  'authors' | 'averageRating' | 'ratings'
>;

export interface BookRatingsProps {
  bookId: string;
  userId: string;
  score: number;
  ratedAt: string;
  user: {
    id: string;
    firstName: string;
  };
}

export const starLabels: { [index: string]: string } = {
  0.5: 'Useless',
  1: 'Useless+',
  1.5: 'Poor',
  2: 'Poor+',
  2.5: 'Ok',
  3: 'Ok+',
  3.5: 'Good',
  4: 'Good+',
  4.5: 'Excellent',
  5: 'Excellent+',
};

export const PAGE_SIZE = 6;

export const SORT_VALUE = ['published_at', 'price'];
export enum BookType {
  NET_Framework = ".NET Framework",
  ThreeD = "3D",
  ActionScript = "ActionScript",
  Active_Directory = "Active Directory",
  Administration = "Administration",
  Agile = "Agile",
  Ajax = "Ajax",
  Algorithms = "Algorithms",
  Amazon_Kindle_Fire = "Amazon Kindle Fire",
  Analytics = "Analytics",
  Android = "Android",
  Angular = "Angular",
  AngularJS = "AngularJS",
  Ansible = "Ansible",
  Apache = "Apache",
  Apache_Camel = "Apache Camel",
  Apache_Cassandra = "Apache Cassandra",
  Apache_Kafka = "Apache Kafka",
  Apache_Spark = "Apache Spark",
  API = "API",
  App_Store = "App Store",
  Arduino = "Arduino",
  ASP = "ASP",
  ASP_NET = "ASP.NET",
  Assembler = "Assembler",
  Audio = "Audio",
  AutoCAD = "AutoCAD",
  AWS = "AWS",
  Backbone = "Backbone",
  bash = "bash",
  Basic = "Basic",
  Big_Data = "Big Data",
  Bitcoin = "Bitcoin",
  Blockchain = "Blockchain",
  Bootstrap = "Bootstrap",
  BSD = "BSD",
  Business = "Business",
  C_Sharp = "C#",
  C_Plus_Plus = "C++",
  Cisco = "Cisco",
  Citrix = "Citrix",
  Clojure = "Clojure",
  Cloud = "Cloud",
  Cocoa = "Cocoa",
  Cocos2D = "Cocos2D",
  CouchDB = "CouchDB",
  CSS = "CSS",
  CSS3 = "CSS3",
  Cucumber = "Cucumber",
  Dart = "Dart",
  Data_Science = "Data Science",
  Database = "Database",
  Delphi = "Delphi",
  Design = "Design",
  DevOps = "DevOps",
  Django = "Django",
  Docker = "Docker",
  Dojo = "Dojo",
  DOM = "DOM",
  Drupal = "Drupal",
  Eclipse = "Eclipse",
  EJB = "EJB",
  Elixir = "Elixir",
  Erlang = "Erlang",
  Ethereum = "Ethereum",
  F_Sharp = "F#",
  Facebook = "Facebook",
  Fedora = "Fedora",
  Firebug = "Firebug",
  Flash = "Flash",
  Flex = "Flex",
  Flutter = "Flutter",
  Fonts = "Fonts",
  For_Dummies = "For Dummies",
  Framework = "Framework",
  FreeBSD = "FreeBSD",
  Games_Development = "Games Development",
  GIMP = "GIMP",
  GIS = "GIS",
  Git = "Git",
  Go = "Go",
  Google = "Google",
  Grails_Framework = "Grails Framework",
  Graph = "Graph",
  Groovy = "Groovy",
  Hack = "Hack",
  Hacking = "Hacking",
  Hadoop = "Hadoop",
  Haskell = "Haskell",
  Head_First = "Head First",
  Hibernate = "Hibernate",
  Hive = "Hive",
  HTML = "HTML",
  HTML5 = "HTML5",
  Hyper_V = "Hyper-V",
  IaaS = "IaaS",
  IBM = "IBM",
  IDE = "IDE",
  IIS = "IIS",
  In_Action = "In Action",
  InDesign = "InDesign",
  Internet_of_Things = "Internet of Things",
  iOS = "iOS",
  iPad = "iPad",
  iPhone = "iPhone",
  Java = "Java",
  JavaFX = "JavaFX",
  JavaScript = "JavaScript",
  Jenkins = "Jenkins",
  JIRA = "JIRA",
  Joomla = "Joomla",
  jQuery = "jQuery",
  JSON = "JSON",
  Julia = "Julia",
  Juniper = "Juniper",
  Knockout = "Knockout",
  Kotlin = "Kotlin",
  Kubernetes = "Kubernetes",
  LaTeX = "LaTeX",
  LEGO = "LEGO",
  Linux = "Linux",
  Lisp = "Lisp",
  Lua = "Lua",
  Mac = "Mac",
  Machine_Learning = "Machine Learning",
  MapReduce = "MapReduce",
  MariaDB = "MariaDB",
  MATLAB = "MATLAB",
  Media = "Media",
  Microsoft = "Microsoft",
  Microsoft_Access = "Microsoft Access",
  Microsoft_Azure = "Microsoft Azure",
  Microsoft_Excel = "Microsoft Excel",
  Microsoft_Office = "Microsoft Office",
  Microsoft_Power_BI = "Microsoft Power BI",
  Microsoft_Word = "Microsoft Word",
  Mobile = "Mobile",
  MongoDB = "MongoDB",
  Munin = "Munin",
  MVC = "MVC",
  MySQL = "MySQL",
  Nagios = "Nagios",
  NetBeans = "NetBeans",
  Network = "Network",
  Neural_Networks = "Neural Networks",
  Nginx = "Nginx",
  Node = "Node",
  Node_js = "Node.js",
  NoSQL = "NoSQL",
  NumPy = "NumPy",
  Nutshell = "Nutshell",
  Objective_C = "Objective-C",
  OpenBSD = "OpenBSD",
  OpenGL = "OpenGL",
  Optimization = "Optimization",
  Oracle = "Oracle",
  Outlook = "Outlook",
  PaaS = "PaaS",
  Panda3D = "Panda3D",
  Patterns = "Patterns",
  Perl = "Perl",
  Phone_Development = "Phone Development",
  PhoneGap = "PhoneGap",
  Photoshop = "Photoshop",
  PHP = "PHP",
  PlayStation = "PlayStation",
  PostgreSQL = "PostgreSQL",
  PowerShell = "PowerShell",
  Programming = "Programming",
  Project = "Project",
  Python = "Python",
  Qt = "Qt",
  RabbitMQ = "RabbitMQ",
  Rails = "Rails",
  Raspberry_Pi = "Raspberry Pi",
  React = "React",
  Redis = "Redis",
  Redmine = "Redmine",
  Regular_Expressions = "Regular Expressions",
  Ruby = "Ruby",
  Ruby_on_Rails = "Ruby on Rails",
  Rust = "Rust",
  Sams_Teach_Yourself = "Sams Teach Yourself",
  SAP = "SAP",
  Sass = "Sass",
  Scala = "Scala",
  SDK = "SDK",
  Security = "Security",
  SEO = "SEO",
  Server = "Server",
  SharePoint = "SharePoint",
  Shell = "Shell",
  Silverlight = "Silverlight",
  SOA = "SOA",
  SOAP = "SOAP",
  Software = "Software",
  Solaris = "Solaris",
  Sphinx = "Sphinx",
  Splunk = "Splunk",
  Spring = "Spring",
  SQL = "SQL",
  Subversion = "Subversion",
  Swift = "Swift",
  TensorFlow = "TensorFlow",
  Testing = "Testing",
  Titanium = "Titanium",
  Training_Kit = "Training Kit",
  Tuning = "Tuning",
  Twitter = "Twitter",
  TypeScript = "TypeScript",
  Ubuntu = "Ubuntu",
  UML = "UML",
  Unity = "Unity",
  Unix = "Unix",
  VB = "VB",
  VBA = "VBA",
  Visual_Basic = "Visual Basic",
  Visual_Studio = "Visual Studio",
  Visualization = "Visualization",
  VMM = "VMM",
  Vue_js = "Vue.js",
  WebGL = "WebGL",
  WebSocket = "WebSocket",
  Wi_Fi = "Wi-Fi",
  Wii = "Wii",
  Windows = "Windows",
  WordPress = "WordPress",
  WPF = "WPF",
  XAML = "XAML",
  Xbox = "Xbox",
  Xcode = "Xcode",
  XML = "XML",
  Yahoo = "Yahoo",
}